# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0005_auto_20160711_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
