# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0007_auto_20160712_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='StuId',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
