# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0011_auto_20160716_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_teacher',
            name='teacherName',
        ),
    ]
