# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0012_remove_account_teacher_teachername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classinfo',
            old_name='classCode',
            new_name='inviteCode',
        ),
    ]
