# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0018_auto_20160720_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_pick',
            old_name='stuId',
            new_name='StuId',
        ),
    ]
