# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=20)),
                ('teacherName', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
