# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0008_student_info_stuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_pick',
            name='username',
        ),
        migrations.AddField(
            model_name='course_pick',
            name='StuId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testCon.Student_Info', to_field='StuId'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_info',
            name='StuId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
