# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0009_auto_20160712_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_pick',
            name='StuId',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course_pick',
            name='className',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
