# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0010_auto_20160713_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_teacher',
            name='teacherName',
            field=models.CharField(default='TeacherName', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classinfo',
            name='classCode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classinfo',
            name='username',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account_teacher',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
