# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0013_auto_20160716_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='inviteCode',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='username',
        ),
        migrations.AlterField(
            model_name='account_teacher',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
