# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0014_auto_20160717_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='inviteCode',
            field=models.CharField(default=123456, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classinfo',
            name='username',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account_teacher',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
