# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0015_auto_20160717_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='Gender',
            new_name='Sex',
        ),
    ]
