# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0016_auto_20160718_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='Sex',
            field=models.CharField(max_length=10),
        ),
    ]
