# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testCon', '0017_auto_20160718_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_pick',
            old_name='StuId',
            new_name='stuId',
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='inviteCode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
