# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_auto_20160725_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='username',
            new_name='account',
        ),
    ]
