# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_auto_20160725_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='gender',
            new_name='sex',
        ),
        migrations.AddField(
            model_name='personal',
            name='birthday',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
